EASY-2136: Content-Length header in easy-bag-store response
DANS-KNAW/easy-solr4files-index pull request #42
Opened 2019-06-13 11:30 UTC by vesaakerman

Fixes EASY-2136

#### When applied it will
* read the file size from `File-Size` header
* handle correctly the situation when the ` File-Size` header is absent

#### Where should the reviewer @DANS-KNAW/easy start?

#### How should this be manually tested?

#### Related pull requests on github
repo                       | PR                | note
-------------------------- | ----------------- | ----
easy-bag-store                      | [#93](https://github.com/DANS-KNAW/easy-bag-store/pull/93)     | ..

2019-06-13 13:38 UTC, rvanheest approved these changes

2019-06-14 14:30 UTC, jo-pol requested changes

2019-06-14 14:30 UTC, jo-pol commented on src/main/scala/nl.knaw.dans.easy.solr4files/package.scala
> +            response.header("File-Size")
Please rename the method accordingly.

2019-06-28 11:09 UTC, janvanmansum commented
As documented in my comment in EASY-2136, we are going for a different solution. Closing this PR. @vesaakerman : please open a new one for the new solution.

2019-06-28 11:09 UTC, closed without merging